apiVersion: v1
kind: Service
metadata:
  name: nzo1ucxz-4543-development-svc
  namespace: qb-prototypes
spec:
  selector:
    app: nzo1ucxz-4543-development
  ports:
  - port: 80
    targetPort: 3000
